# pasajeros/docker-compose.yml
version: "3.8"
services:
  pasajeros-db:
    image: postgres:13
    environment:
      POSTGRES_USER: jdrt
      POSTGRES_PASSWORD: traxi_prueba
      POSTGRES_DB: pasajeros
    ports:
      - "5432:5432"
    volumes:
      - pasajeros-db-data:/var/lib/postgresql/data

  pasajeros:
    build: .
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://jdrt:traxi_prueba@pasajeros-db:5432/pasajeros
      RABBITMQ_HOST: 172.17.0.1
    depends_on:
      - pasajeros-db

volumes:
  pasajeros-db-data: