version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Interfaz de administración
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    hostname: rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq-data:
